### ISSUE TITLE
run_example.sh is outdated

### ISSUE THREAD

**Issue by rykovan** [jakelever/pgxmine#3]
[createKB.py](https://github.com/jakelever/pgxmine/blob/9467f6a7d3457c2ebf2a4559b9aed684fc320504/run_example.sh#L13) is called without `--relevantMeSH`:

```
createKB.py: error: the following arguments are required: --relevantMeSH
```

**Comment by jakelever** [comment]
Agreed. This had got out-of-date as I'd added some experimental bits to it. I've updated the example input data and the run_example script accordingly. Hopefully works a little better.

**Comment by rykovan** [comment]
Thank you very much, now everything works flawlessly.
